backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: Svingen/images

collections:
  - name: settings
    label: Innstillinger
    files:
      - name: general
        label: Generelt
        file: Svingen/data/settings.json
        fields:
          - { label: Restaurantnavn, name: name, widget: string }
          - { label: Telefon, name: phone, widget: string }
          - { label: Adresse, name: address, widget: string }
          - { label: Åpningstider hverdager, name: weekdays, widget: string }
          - { label: Åpningstider helg, name: weekend, widget: string }
